# Generated by Django 4.0.2 on 2022-02-09 22:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bombas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tanques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=15)),
                ('volume_m3', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 2, 9, 22, 10, 36, 483208, tzinfo=utc), editable=False)),
                ('litros', models.DecimalField(decimal_places=6, max_digits=12)),
                ('valor_abastecido', models.DecimalField(decimal_places=6, max_digits=12)),
                ('valor_de_imposto', models.DecimalField(decimal_places=6, max_digits=12)),
                ('bomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posto.bombas')),
            ],
        ),
        migrations.AddField(
            model_name='bombas',
            name='tanque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posto.tanques'),
        ),
    ]
